[package]
name = "swizzleflow"
version = "0.1.0"
authors = ["Krzysztof Drewniak <krzysdrewniak@gmail.com>"]
edition = "2018"

[dependencies]
blas-src = { version = "0.2", features = ["openblas"] }
ndarray = { version = "0.12", features = ["blas"] }
smallvec = "0.6.9"
